export default {
    SET_ORGANISATION_INVERTERS: 'SET_ORGANISATION_INVERTERS',
    LOAD_MORE_ORGANISATION_INVERTERS: 'LOAD_MORE_ORGANISATION_INVERTERS',
    FETCH_ORGANISATION_INVERTERS: 'FETCH_ORGANISATION_INVERTERS',
    ADD_ORGANISATION_INVERTER: 'ADD_ORGANISATION_INVERTER',
    DELETE_ORGANISATION_INVERTER: 'DELETE_ORGANISATION_INVERTER',
    GET_ORGANISATION_INVERTER: 'GET_ORGANISATION_INVERTER'
};