export default {
    SET_ORGANISATION_PANELS: 'SET_ORGANISATION_PANELS',
    LOAD_MORE_ORGANISATION_PANELS: 'LOAD_MORE_ORGANISATION_PANELS',
    FETCH_ORGANISATION_PANELS: 'FETCH_ORGANISATION_PANELS',
    ADD_ORGANISATION_PANEL: 'ADD_ORGANISATION_PANEL',
    DELETE_ORGANISATION_PANEL: 'DELETE_ORGANISATION_PANEL',
    GET_ORGANISATION_PANEL: 'GET_ORGANISATION_PANEL'
};